# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from application.models.base_model_ import Model
from application.util import util


class RequirementPopularity(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, popularity: float=None):  # noqa: E501
        """RequirementPopularity - a model defined in Swagger

        :param id: The id of this RequirementPopularity.  # noqa: E501
        :type id: int
        :param popularity: The popularity of this RequirementPopularity.  # noqa: E501
        :type popularity: float
        """
        self.swagger_types = {
            'id': int,
            'popularity': float
        }

        self.attribute_map = {
            'id': 'id',
            'popularity': 'popularity'
        }

        self._id = id
        self._popularity = popularity

    @classmethod
    def from_dict(cls, dikt) -> 'RequirementPopularity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequirementPopularity of this RequirementPopularity.  # noqa: E501
        :rtype: RequirementPopularity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this RequirementPopularity.


        :return: The id of this RequirementPopularity.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this RequirementPopularity.


        :param id: The id of this RequirementPopularity.
        :type id: int
        """

        self._id = id

    @property
    def popularity(self) -> float:
        """Gets the popularity of this RequirementPopularity.


        :return: The popularity of this RequirementPopularity.
        :rtype: float
        """
        return self._popularity

    @popularity.setter
    def popularity(self, popularity: float):
        """Sets the popularity of this RequirementPopularity.


        :param popularity: The popularity of this RequirementPopularity.
        :type popularity: float
        """

        self._popularity = popularity
